### ISSUE TITLE
Image view has wrong position from Landscape rotation

### ISSUE THREAD

**Issue by viktor-symphony** [vowed21/HWViewPager#1]
![ios simulator screen shot feb 4 2015 9 53 22 am](https://cloud.githubusercontent.com/assets/8387484/6046063/b06ac318-ac53-11e4-9961-853d0480eb2e.png)

**Comment by vowed21** [comment]
Fix it.
Thank you for Review.

https://github.com/vowed21/HWViewPager/commit/972fac632fc17dcbc29ede113ba0b4908c6379d9#diff-0
