### ISSUE TITLE
cocoapod대응

### ISSUE THREAD

**Issue by hmhv** [vowed21/HWViewPager#2]
좋아보입니다..^^

cocoapod에 대응 해주시겠어요?

**Comment by vowed21** [comment]
저기, 죄송한데... 제가 초보 개발자라 ㅋ
코코아팟에 어떻게 대응하죠? ㅡ,.ㅡ?

**Comment by hmhv** [comment]
http://hmhv.info/2015/02/add-library-to-cocoapods-k/

이거 한번 읽어보시고 해보세요. 어렵지 않아요..^^

**Comment by vowed21** [comment]
https://raw.githubusercontent.com/CocoaPods/Specs/03175f63a9b438ef62630285486f01613996716c/Specs/HWViewPager/0.0.1/HWViewPager.podspec.json

된걸까요??

**Comment by hmhv** [comment]
복사해야할 파일이 잘못 지정되있네요 그리고 버전도 1.0으로 태그 만들고 지정해주세요.

cocoapod을 한번 사용해 보고 직접 확인해보세요.. 뭐 급할꺼 없으니..ㅎ

**Comment by vowed21** [comment]
이제야 코코아팟에 적용을 시켰네요. 굉장히 오래걸렸네요 ㅠㅠ

보내주신 블로그참고해서 이번에 스위프트 버전 같이 만들면서 같이 적용했습니다.
정말정말 감사드립니다.~!^^
