### ISSUE TITLE
How to set page?

### ISSUE THREAD

**Issue by willyantows** [vowed21/HWViewPager#5]

**Comment by vowed21** [comment]
This version is not supported.

please, use "HWSwiftyViewPager"
`func viewPager.setPage(pageNum)`

https://github.com/vowed21/HWSwiftyViewPager

**Comment by willyantows** [comment]
Oh, thank you
Btw, I already modified your code to support setPage.

On 12 January 2016 at 10:30, Kim Hyun Woo notifications@github.com wrote:

> This version are not support.
> 
> please use "HWSwiftyViewPager"
> 
> https://github.com/vowed21/HWSwiftyViewPager
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vowed21/HWViewPager/issues/5#issuecomment-170772953.

## 

Best Regards,

Willyanto Wijaya Sulaiman
m : +62.817.9695.652
e  : willyanto.wijaya@gmail.com

_www.spots.co.id http://www.spots.co.id_

**Comment by vowed21** [comment]
Great, 
Now, 1.2 version (cocoapod)
Support setPage 

```
-(void) setPage:(NSInteger)page isAnimation:(BOOL)isAnim
```

Thank you,
